CLIENT_HTML = r'''<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>CNC Master Cloud — Engineering Client</title>
<style>
:root{color-scheme:dark;--bg:#071018;--panel:#101b25;--panel2:#152432;--line:#294154;--text:#edf5fb;--muted:#93a8b8;--accent:#3b91e8;--ok:#49c987;--warn:#ffc766;--danger:#ff6d75}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.4 Inter,system-ui,-apple-system,Segoe UI,sans-serif}
button,input,select,textarea{font:inherit;color:var(--text);background:#0c1720;border:1px solid var(--line);border-radius:9px;padding:9px 10px}button{cursor:pointer}button:hover{border-color:var(--accent)}button.primary{background:var(--accent);border-color:var(--accent);font-weight:700}button.good{background:#176743;border-color:#24915f}.danger{color:#ff9aa1}.muted{color:var(--muted)}
header{display:flex;gap:16px;align-items:center;padding:14px 18px;background:#0d1821;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:10}header h1{font-size:17px;margin:0}header .badge{background:#17324a;padding:5px 9px;border-radius:999px;color:#a8d7ff}.spacer{flex:1}
.app{display:grid;grid-template-columns:330px minmax(620px,1fr) 410px;gap:10px;padding:10px;height:calc(100vh - 62px)}.panel{background:var(--panel);border:1px solid var(--line);border-radius:13px;overflow:auto}.section{padding:13px;border-bottom:1px solid var(--line)}.section h2{font-size:14px;margin:0 0 10px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.field{display:grid;gap:4px}.field label{font-size:12px;color:var(--muted)}.field input,.field select{width:100%;min-width:0}.row{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.row>*{min-width:0}
.canvasWrap{height:100%;display:grid;grid-template-rows:auto 1fr auto}.toolbar{padding:9px;display:flex;gap:6px;flex-wrap:wrap;border-bottom:1px solid var(--line);background:var(--panel)}.toolbar button.active{background:#174f7d;border-color:#4da8ef}.stage{position:relative;min-height:400px;background:#061018;overflow:hidden}.stage canvas{position:absolute;inset:0;width:100%;height:100%}.statusbar{padding:8px 12px;border-top:1px solid var(--line);color:var(--muted);display:flex;gap:20px;min-height:37px}
.ops{display:grid;gap:8px}.op{border:1px solid var(--line);border-radius:10px;background:var(--panel2);padding:9px}.opHead{display:flex;align-items:center;gap:7px;margin-bottom:8px}.opHead strong{flex:1}.opGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.opGrid input{width:100%;padding:7px}.small{font-size:12px}.toolResult{padding:8px;background:#0b151e;border-radius:8px;margin-top:7px;color:#c6d7e5;min-height:34px}
.tabs{display:flex;gap:4px;padding:8px;border-bottom:1px solid var(--line);position:sticky;top:0;background:var(--panel);z-index:2}.tabs button{padding:7px 9px}.tabs button.active{background:#194f78}.tab{display:none;padding:12px}.tab.active{display:block}.resultCard{border:1px solid var(--line);border-radius:10px;padding:10px;margin-bottom:9px;background:#0d1821}.resultCard h3{font-size:14px;margin:0 0 8px}.kv{display:grid;grid-template-columns:1fr auto;gap:5px 10px}.kv div:nth-child(odd){color:var(--muted)}pre{white-space:pre-wrap;word-break:break-word;background:#050b10;border:1px solid var(--line);border-radius:10px;padding:10px;max-height:58vh;overflow:auto}ol{padding-left:22px}.warn{border-left:3px solid var(--warn);padding:8px 10px;background:#2a2415;margin:7px 0}.ok{border-left:3px solid var(--ok);padding:8px 10px;background:#12271e;margin:7px 0}
.modal{position:fixed;inset:0;background:#000b;display:none;align-items:center;justify-content:center;z-index:50}.modal.open{display:flex}.modalBox{width:min(900px,94vw);max-height:88vh;overflow:auto;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:14px}.toolList{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.toolItem{border:1px solid var(--line);border-radius:9px;padding:9px;cursor:pointer}.toolItem:hover{border-color:var(--accent)}
@media(max-width:1200px){.app{grid-template-columns:300px 1fr}.results{grid-column:1/-1;max-height:600px}.stage{min-height:620px}}@media(max-width:760px){.app{display:block;height:auto}.panel{margin-bottom:10px}.stage{height:580px}.opGrid{grid-template-columns:1fr 1fr}.toolList{grid-template-columns:1fr}}
</style>
</head>
<body>
<header>
  <h1>⚙️ CNC Master Cloud — Engineering Client</h1><span class="badge">v2.0.0</span>
  <span class="muted">Контур · PDF · Stock Removal · G-код</span><span class="spacer"></span>
  <button id="loadProjects">📂 Проекты</button><button id="saveBtn">💾 Сохранить</button><button id="generateBtn" class="primary">▶ Рассчитать</button>
</header>
<div class="app">
<aside class="panel">
  <div class="section"><h2>📁 Проект</h2>
    <div class="field"><label>Название</label><input id="title" value="Деталь из PDF"></div>
    <div class="grid2" style="margin-top:8px"><div class="field"><label>Telegram ID</label><input id="telegramId" inputmode="numeric"></div><div class="field"><label>ID станка</label><input id="machineId" inputmode="numeric"></div></div>
    <div class="field" style="margin-top:8px"><label>Стойка</label><select id="controller"><option>Siemens SINUMERIK 828D</option><option>Siemens SINUMERIK 840D</option><option>Fanuc 0i-TF</option><option>Haas NGC</option><option>Generic ISO</option></select></div>
  </div>
  <div class="section"><h2>🧱 Фактическая заготовка</h2>
    <div class="grid2"><div class="field"><label>Наружный Ø, мм</label><input id="stockD" type="number" step="0.01" value="100"></div><div class="field"><label>Длина, мм</label><input id="stockL" type="number" step="0.01" value="80"></div></div>
    <div class="grid2" style="margin-top:8px"><div class="field"><label>Отверстие Ø, мм</label><input id="stockId" type="number" step="0.01" value="0"></div><div class="field"><label>Макс. обороты</label><input id="maxRpm" type="number" value="3500"></div></div>
  </div>
  <div class="section"><h2>📄 Чертёж PDF</h2>
    <div class="field"><input id="pdfFile" type="file" accept="application/pdf"></div>
    <div class="row" style="margin-top:7px"><input id="pdfPage" type="number" min="1" value="1" style="width:75px"><button id="uploadPdf">Загрузить страницу</button></div>
    <div id="pdfInfo" class="small muted" style="margin-top:7px">PDF не загружен.</div>
  </div>
  <div class="section"><h2>📐 Масштаб и координаты</h2>
    <div class="field"><label>Известный размер между 2 точками, мм</label><input id="referenceMm" type="number" step="0.001" value="100"></div>
    <div class="row" style="margin-top:8px"><button data-mode="calibrate">1. Калибровать</button><button data-mode="origin">2. Задать X0/Z0</button></div>
    <label class="small"><input id="diameterMode" type="checkbox" checked> Высота от оси — радиус, X пересчитать ×2</label>
    <div id="scaleInfo" class="small muted" style="margin-top:6px">Масштаб не задан.</div>
  </div>
  <div class="section"><h2>📍 Точки контура X/Z</h2>
    <textarea id="contourText" rows="6" placeholder="X70 Z0&#10;X70 Z-20&#10;X50 Z-25"></textarea>
    <div class="row" style="margin-top:7px"><button id="applyContour">Применить точные значения</button><button id="exportContour">Обновить из рисунка</button></div>
  </div>
  <div class="section"><h2>🧩 Операции</h2>
    <div class="row">
      <select id="newOp"><option value="turn_rough">Черновое точение</option><option value="turn_finish">Чистовое точение</option><option value="face">Торцевание</option><option value="bore_rough">Черновая расточка</option><option value="bore_finish">Чистовая расточка</option><option value="drill">Сверление</option><option value="groove">Канавка</option><option value="part">Отрезка</option><option value="thread_od">Наружная резьба</option><option value="thread_id">Внутренняя резьба</option><option value="mill">Фрезерование</option></select>
      <button id="addOp">➕</button>
    </div>
    <div id="operations" class="ops" style="margin-top:9px"></div>
  </div>
</aside>

<main class="panel canvasWrap">
  <div class="toolbar">
    <button data-mode="draw" class="active">✏️ Контур</button><button id="useAuto">✨ Автоконтур</button><button id="undo">↩ Отменить точку</button><button id="clearContour">🗑 Очистить</button>
    <button id="fit">⛶ Вписать</button><button id="togglePdf">👁 PDF</button>
    <span class="muted" style="align-self:center">Щёлкайте от торца Z0 вглубь детали.</span>
  </div>
  <div class="stage"><canvas id="canvas"></canvas></div>
  <div class="statusbar"><span id="cursor">X — / Z —</span><span id="pointCount">Точек: 0</span><span id="modeStatus">Режим: контур</span></div>
</main>

<section class="panel results">
  <div class="tabs"><button data-tab="preview" class="active">Графика</button><button data-tab="stock">Stock Removal</button><button data-tab="steps">По инструментам</button><button data-tab="gcode">G-код</button></div>
  <div id="preview" class="tab active"><div class="muted">Нажмите «Рассчитать», чтобы построить траектории и итоговую форму.</div><canvas id="resultCanvas" width="760" height="520" style="width:100%;margin-top:12px;background:#061018;border:1px solid var(--line);border-radius:10px"></canvas><div id="summary"></div></div>
  <div id="stock" class="tab"></div>
  <div id="steps" class="tab"></div>
  <div id="gcode" class="tab"><div class="row"><button id="copyGcode">📋 Копировать</button><button id="downloadGcode">⬇ Скачать MPF</button></div><pre id="gcodeText">G-код ещё не рассчитан.</pre></div>
</section>
</div>

<div id="toolModal" class="modal"><div class="modalBox"><div class="row"><h2 style="margin:0;flex:1">🔩 Выбор инструмента из каталога</h2><button id="closeTools">✕</button></div><div class="grid3" style="margin:12px 0"><input id="toolSearch" placeholder="Маркировка или название"><select id="toolCategory"><option value="">Все категории</option><option value="turning_holders">Токарные державки</option><option value="boring_bars">Расточные державки</option><option value="turning_inserts">Токарные пластины</option><option value="grooving_parting">Канавки / отрезка</option><option value="threading">Резьба</option><option value="drills">Сверла</option><option value="mills">Фрезы</option><option value="toolholding">Оснастка</option></select><button id="searchTools">Найти</button></div><div id="toolList" class="toolList"></div></div></div>
<div id="projectModal" class="modal"><div class="modalBox"><div class="row"><h2 style="margin:0;flex:1">📂 Сохранённые проекты</h2><button id="closeProjects">✕</button></div><div id="projectList" style="display:grid;gap:8px;margin-top:12px"></div></div></div>
<script>
const OP_LABELS={face:'Торцевание',turn_rough:'Черновое точение',turn_finish:'Чистовое точение',bore_rough:'Черновая расточка',bore_finish:'Чистовая расточка',drill:'Сверление',groove:'Канавка',part:'Отрезка',thread_od:'Наружная резьба',thread_id:'Внутренняя резьба',mill:'Фрезерование'};
const DEFAULTS={face:[120,.18,1.5],turn_rough:[130,.25,2],turn_finish:[170,.10,.3],bore_rough:[100,.18,1],bore_finish:[140,.08,.25],drill:[70,.12,0],groove:[90,.08,0],part:[75,.06,0],thread_od:[45,1.5,0],thread_id:[35,1.5,0],mill:[120,300,1]};
const state={mode:'draw',pdfImage:null,pdfVisible:true,pdfCandidate:[],pointsPx:[],scalePxMm:null,origin:null,calibration:[],operations:[],result:null,view:{scale:1,ox:0,oy:0},activeOp:null};
const $=id=>document.getElementById(id);const canvas=$('canvas'),ctx=canvas.getContext('2d');
function resize(){const r=canvas.parentElement.getBoundingClientRect();canvas.width=Math.max(600,Math.floor(r.width*devicePixelRatio));canvas.height=Math.max(420,Math.floor(r.height*devicePixelRatio));ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);draw();}
addEventListener('resize',resize);setTimeout(resize,0);
function setMode(mode){state.mode=mode;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('modeStatus').textContent='Режим: '+({draw:'контур',calibrate:'калибровка',origin:'начало координат'}[mode]||mode);}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
function imageToCanvas(px,py){if(!state.pdfImage)return[px,py];const cw=canvas.clientWidth,ch=canvas.clientHeight,iw=state.pdfImage.width,ih=state.pdfImage.height;const s=Math.min(cw/iw,ch/ih)*state.view.scale;const x=(cw-iw*s)/2+state.view.ox+px*s,y=(ch-ih*s)/2+state.view.oy+py*s;return[x,y];}
function canvasToImage(x,y){if(!state.pdfImage)return[x,y];const cw=canvas.clientWidth,ch=canvas.clientHeight,iw=state.pdfImage.width,ih=state.pdfImage.height;const s=Math.min(cw/iw,ch/ih)*state.view.scale;return[(x-(cw-iw*s)/2-state.view.ox)/s,(y-(ch-ih*s)/2-state.view.oy)/s];}
function pixelToMachine(p){if(!state.origin||!state.scalePxMm)return null;const mul=$('diameterMode').checked?2:1;return{z:(p.x-state.origin.x)/state.scalePxMm,x:Math.abs(p.y-state.origin.y)/state.scalePxMm*mul};}
function machinePoints(){return state.pointsPx.map(pixelToMachine).filter(Boolean).map(p=>({z:+p.z.toFixed(4),x:+p.x.toFixed(4)}));}
function machineToPixel(p){if(!state.origin||!state.scalePxMm)return null;const mul=$('diameterMode').checked?2:1;return{x:state.origin.x+p.z*state.scalePxMm,y:state.origin.y-(p.x/mul)*state.scalePxMm}}
function ensureManualFrame(){if(state.origin&&state.scalePxMm)return;const l=+$('stockL').value||100,d=+$('stockD').value||100;state.scalePxMm=Math.min(canvas.clientWidth*.7/l,canvas.clientHeight*.65/(d/2));state.origin={x:canvas.clientWidth*.85,y:canvas.clientHeight*.82};$('scaleInfo').textContent=`Ручной масштаб: ${state.scalePxMm.toFixed(4)} px/мм`;}
function syncContourText(){const pts=machinePoints();$('contourText').value=pts.map(p=>`X${p.x.toFixed(3)} Z${p.z.toFixed(3)}`).join('\n')}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#061018';ctx.fillRect(0,0,w,h);
 if(state.pdfImage&&state.pdfVisible){const [x,y]=imageToCanvas(0,0),[x2,y2]=imageToCanvas(state.pdfImage.width,state.pdfImage.height);ctx.globalAlpha=.48;ctx.drawImage(state.pdfImage,x,y,x2-x,y2-y);ctx.globalAlpha=1;}
 drawGrid();drawStock();drawCandidate();drawCalibration();drawOrigin();drawContour();}
function drawGrid(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.strokeStyle='#122431';ctx.lineWidth=1;for(let x=0;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}}
function drawStock(){if(!state.origin||!state.scalePxMm)return;const d=+($('stockD').value||0),l=+($('stockL').value||0),mul=$('diameterMode').checked?2:1;const top={x:state.origin.x,y:state.origin.y-(d/mul)*state.scalePxMm},end={x:state.origin.x-l*state.scalePxMm,y:state.origin.y};const [x0,y0]=imageToCanvas(top.x,top.y),[x1,y1]=imageToCanvas(end.x,state.origin.y);ctx.fillStyle='#46758a22';ctx.strokeStyle='#57b8d9';ctx.lineWidth=2;ctx.fillRect(x1,y0,x0-x1,y1-y0);ctx.strokeRect(x1,y0,x0-x1,y1-y0);}
function drawCandidate(){if(!state.pdfCandidate.length)return;ctx.strokeStyle='#ffc766';ctx.setLineDash([6,5]);ctx.beginPath();state.pdfCandidate.forEach((p,i)=>{const q=imageToCanvas(p.px,p.py);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.stroke();ctx.setLineDash([])}
function drawCalibration(){if(!state.calibration.length)return;ctx.fillStyle='#ffc766';state.calibration.forEach(p=>{const q=imageToCanvas(p.x,p.y);ctx.beginPath();ctx.arc(q[0],q[1],5,0,Math.PI*2);ctx.fill()});if(state.calibration.length===2){const a=imageToCanvas(state.calibration[0].x,state.calibration[0].y),b=imageToCanvas(state.calibration[1].x,state.calibration[1].y);ctx.strokeStyle='#ffc766';ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}}
function drawOrigin(){if(!state.origin)return;const q=imageToCanvas(state.origin.x,state.origin.y);ctx.strokeStyle='#49c987';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(q[0]-12,q[1]);ctx.lineTo(q[0]+12,q[1]);ctx.moveTo(q[0],q[1]-12);ctx.lineTo(q[0],q[1]+12);ctx.stroke();ctx.fillStyle='#49c987';ctx.fillText('X0/Z0',q[0]+8,q[1]-8)}
function drawContour(){if(!state.pointsPx.length)return;ctx.strokeStyle='#ff6d75';ctx.lineWidth=3;ctx.beginPath();state.pointsPx.forEach((p,i)=>{const q=imageToCanvas(p.x,p.y);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.stroke();ctx.fillStyle='#ff9298';state.pointsPx.forEach((p,i)=>{const q=imageToCanvas(p.x,p.y);ctx.beginPath();ctx.arc(q[0],q[1],4,0,Math.PI*2);ctx.fill();ctx.fillText(String(i+1),q[0]+5,q[1]-5)});$('pointCount').textContent='Точек: '+state.pointsPx.length;}
canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,p=canvasToImage(x,y);const point={x:p[0],y:p[1]};if(state.mode==='draw'){state.pointsPx.push(point);syncContourText()}else if(state.mode==='origin'){state.origin=point;setMode('draw')}else if(state.mode==='calibrate'){state.calibration.push(point);if(state.calibration.length===2){const dx=state.calibration[1].x-state.calibration[0].x,dy=state.calibration[1].y-state.calibration[0].y,dist=Math.hypot(dx,dy),mm=+$('referenceMm').value;if(dist>0&&mm>0){state.scalePxMm=dist/mm;$('scaleInfo').textContent=`Масштаб: ${state.scalePxMm.toFixed(4)} px/мм`;setMode('origin')}else state.calibration=[]}}draw()});
canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect(),p=canvasToImage(e.clientX-r.left,e.clientY-r.top),m=pixelToMachine({x:p[0],y:p[1]});$('cursor').textContent=m?`X ${m.x.toFixed(3)} / Z ${m.z.toFixed(3)}`:'X — / Z —'});
$('undo').onclick=()=>{state.pointsPx.pop();syncContourText();draw()};$('clearContour').onclick=()=>{if(confirm('Очистить точки контура?')){state.pointsPx=[];syncContourText();draw()}};$('fit').onclick=()=>{state.view={scale:1,ox:0,oy:0};draw()};$('togglePdf').onclick=()=>{state.pdfVisible=!state.pdfVisible;draw()};$('useAuto').onclick=()=>{if(!state.pdfCandidate.length)return alert('Автоконтур не найден. Обведите профиль вручную.');state.pointsPx=state.pdfCandidate.map(p=>({x:p.px,y:p.py}));syncContourText();draw()};
['stockD','stockL','diameterMode'].forEach(id=>$(id).oninput=draw);
$('exportContour').onclick=syncContourText;$('applyContour').onclick=()=>{const lines=$('contourText').value.split(/\n+/),pts=[];for(const line of lines){const mx=line.match(/X\s*(-?\d+(?:[.,]\d+)?)/i),mz=line.match(/Z\s*(-?\d+(?:[.,]\d+)?)/i);if(mx&&mz)pts.push({x:+mx[1].replace(',','.'),z:+mz[1].replace(',','.')});else{const nums=line.match(/-?\d+(?:[.,]\d+)?/g);if(nums&&nums.length>=2)pts.push({x:+nums[0].replace(',','.'),z:+nums[1].replace(',','.')})}}if(pts.length<2)return alert('Нужно минимум две строки X/Z.');ensureManualFrame();state.pointsPx=pts.map(machineToPixel).filter(Boolean);draw()};
$('uploadPdf').onclick=async()=>{const file=$('pdfFile').files[0];if(!file)return alert('Выберите PDF.');const fd=new FormData();fd.append('file',file);fd.append('page_number',$('pdfPage').value||1);fd.append('telegram_id',$('telegramId').value||0);$('pdfInfo').textContent='Обработка PDF…';try{const res=await fetch('/api/v1/client/pdf/analyze',{method:'POST',body:fd});const data=await res.json();if(!res.ok)throw new Error(data.detail||'Ошибка PDF');const img=new Image();img.onload=()=>{state.pdfImage=img;state.pdfCandidate=data.candidate_pixels||[];state.view={scale:1,ox:0,oy:0};$('pdfInfo').innerHTML=`Страница ${data.page}/${data.page_count}; автоконтур: <b>${data.candidate_confidence}</b>; подсказки размеров: ${(data.dimension_hints||[]).slice(0,12).join(', ')||'нет'}`;draw()};img.src=data.image_data_url}catch(err){$('pdfInfo').textContent='Ошибка: '+err.message}};
function addOperation(type){const d=DEFAULTS[type]||[100,.15,1];state.operations.push({id:crypto.randomUUID(),type,tool_no:state.operations.length+1,tool:{code:'НЕ ЗАДАН',name:'Выберите из каталога'},params:{vc:d[0],feed:d[1],ap:d[2],allow_x:type.includes('rough')?.5:0,allow_z:type.includes('rough')?.2:0}});renderOperations()}
$('addOp').onclick=()=>addOperation($('newOp').value);
function renderOperations(){$('operations').innerHTML='';state.operations.forEach((op,index)=>{const el=document.createElement('div');el.className='op';el.innerHTML=`<div class="opHead"><strong>${index+1}. ${OP_LABELS[op.type]}</strong><button data-tool>🔩 Каталог</button><button data-remove class="danger">✕</button></div><div class="opGrid"><label class="field"><span>Т №</span><input data-k="tool_no" value="${op.tool_no}"></label><label class="field"><span>Vc м/мин</span><input data-p="vc" value="${op.params.vc}"></label><label class="field"><span>F</span><input data-p="feed" value="${op.params.feed}"></label><label class="field"><span>ap рад., мм</span><input data-p="ap" value="${op.params.ap}"></label><label class="field"><span>Припуск X Ø</span><input data-p="allow_x" value="${op.params.allow_x||0}"></label><label class="field"><span>Припуск Z</span><input data-p="allow_z" value="${op.params.allow_z||0}"></label></div><div class="toolResult"><b>${op.tool.code}</b> — ${op.tool.name}</div>`;el.querySelector('[data-remove]').onclick=()=>{state.operations.splice(index,1);renderOperations()};el.querySelector('[data-tool]').onclick=()=>openTools(index);el.querySelectorAll('[data-p]').forEach(inp=>inp.oninput=()=>op.params[inp.dataset.p]=+inp.value);el.querySelector('[data-k]').oninput=e=>op.tool_no=+e.target.value;$('operations').appendChild(el)});}
let toolTarget=null;function openTools(index){toolTarget=index;$('toolModal').classList.add('open');searchTools()}$('closeTools').onclick=()=>$('toolModal').classList.remove('open');$('searchTools').onclick=searchTools;
async function searchTools(){const q=encodeURIComponent($('toolSearch').value),cat=encodeURIComponent($('toolCategory').value);$('toolList').textContent='Загрузка…';try{const res=await fetch(`/api/v1/tools?limit=50&q=${q}&category=${cat}`);const data=await res.json();$('toolList').innerHTML='';data.forEach(item=>{const el=document.createElement('div');el.className='toolItem';el.innerHTML=`<b>${item.code}</b><br>${item.name}<div class="small muted">${item.dimensions||''}</div>`;el.onclick=()=>{state.operations[toolTarget].tool=item;$('toolModal').classList.remove('open');renderOperations()};$('toolList').appendChild(el)});if(!data.length)$('toolList').textContent='Ничего не найдено.'}catch(e){$('toolList').textContent='Ошибка каталога: '+e.message}}
function collectPayload(){const points=machinePoints();return{telegram_id:+$('telegramId').value||0,machine_id:+$('machineId').value||0,title:$('title').value,machine:{controller:$('controller').value,max_rpm:+$('maxRpm').value||0},stock:{outer_diameter:+$('stockD').value,inner_diameter:+$('stockId').value||0,length:+$('stockL').value},contour:{mode:'outer',points},operations:state.operations.map(op=>({...op,tool_no:op.tool_no}))}}
$('generateBtn').onclick=async()=>{const payload=collectPayload();if(payload.contour.points.length<2)return alert('Нужно минимум две точки контура.');if(!payload.operations.length)return alert('Добавьте операции.');$('generateBtn').disabled=true;$('generateBtn').textContent='Расчёт…';try{const res=await fetch('/api/v1/client/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.detail||'Ошибка расчёта');state.result=data;renderResult()}catch(e){alert(e.message)}finally{$('generateBtn').disabled=false;$('generateBtn').textContent='▶ Рассчитать'}};
function renderResult(){const r=state.result;$('summary').innerHTML=`<div class="ok">Операций: ${r.summary.operations}; инструментов: ${r.summary.tools}; проходов: ${r.summary.passes}</div>`+(r.warnings||[]).map(w=>`<div class="warn">⚠ ${w}</div>`).join('');$('gcodeText').textContent=r.gcode;renderStock(r);renderSteps(r);drawResult(r)}
function renderStock(r){$('stock').innerHTML=(r.stock_removal||[]).map((card,i)=>`<div class="resultCard"><h3>${i+1}. ${card.operation}</h3><div><b>${card.tool}</b></div><div class="small muted">${card.screen}</div><div class="kv" style="margin-top:9px">${Object.entries(card.fields).map(([k,v])=>`<div>${k}</div><div>${v}</div>`).join('')}</div><h3 style="margin-top:12px">Точки контура X/Z</h3><pre>${card.contour_points.map(p=>`X${p.x.toFixed(3)} Z${p.z.toFixed(3)}`).join('\n')}</pre>${card.notes.map(n=>`<div class="warn">${n}</div>`).join('')}</div>`).join('')||'<div class="muted">Добавьте операцию чернового точения или расточки.</div>'}
function renderSteps(r){$('steps').innerHTML=(r.steps||[]).map(s=>`<div class="resultCard"><h3>${s.number}. ${s.title}</h3><div><b>T${s.tool.tool_no}: ${s.tool.code}</b> — ${s.tool.name}</div><div class="kv" style="margin-top:9px">${Object.entries(s.settings).map(([k,v])=>`<div>${k}</div><div>${v}</div>`).join('')}</div><ol>${s.instructions.map(i=>`<li>${i}</li>`).join('')}</ol></div>`).join('')}
function drawResult(r){const c=$('resultCanvas'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.fillStyle='#061018';x.fillRect(0,0,w,h);const all=[...(r.final_contour||[])];(r.toolpaths||[]).forEach(p=>all.push(...p.points));if(!all.length)return;const minZ=Math.min(...all.map(p=>p.z)),maxZ=Math.max(...all.map(p=>p.z)),maxX=Math.max(r.stock.outer_diameter,...all.map(p=>p.x)),pad=45,sx=(w-2*pad)/Math.max(1,maxZ-minZ),sy=(h-2*pad)/Math.max(1,maxX),tx=z=>pad+(z-minZ)*sx,ty=v=>h-pad-v*sy;x.strokeStyle='#294154';for(let i=0;i<10;i++){const yy=pad+i*(h-2*pad)/9;x.beginPath();x.moveTo(pad,yy);x.lineTo(w-pad,yy);x.stroke()}x.fillStyle='#46758a22';x.strokeStyle='#57b8d9';x.fillRect(tx(minZ),ty(r.stock.outer_diameter),tx(maxZ)-tx(minZ),ty(0)-ty(r.stock.outer_diameter));x.strokeRect(tx(minZ),ty(r.stock.outer_diameter),tx(maxZ)-tx(minZ),ty(0)-ty(r.stock.outer_diameter));(r.toolpaths||[]).forEach((path,i)=>{x.strokeStyle=`hsl(${(i*47)%360} 75% 62%)`;x.lineWidth=1.5;x.beginPath();path.points.forEach((p,j)=>j?x.lineTo(tx(p.z),ty(p.x)):x.moveTo(tx(p.z),ty(p.x)));x.stroke()});x.strokeStyle='#ff6d75';x.lineWidth=4;x.beginPath();r.final_contour.forEach((p,j)=>j?x.lineTo(tx(p.z),ty(p.x)):x.moveTo(tx(p.z),ty(p.x)));x.stroke();x.fillStyle='#dbeaf5';x.fillText('Z, мм',w/2,h-10);x.save();x.translate(14,h/2);x.rotate(-Math.PI/2);x.fillText('X (диаметр), мм',0,0);x.restore()}
$('copyGcode').onclick=()=>navigator.clipboard.writeText($('gcodeText').textContent);$('downloadGcode').onclick=()=>{if(!state.result)return;const blob=new Blob([state.result.gcode],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=($('title').value||'cnc_project').replace(/[^\wа-яА-Я-]+/g,'_')+'.mpf';a.click();URL.revokeObjectURL(a.href)};
$('saveBtn').onclick=async()=>{const payload=collectPayload();try{const res=await fetch('/api/v1/client/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({telegram_id:payload.telegram_id,machine_id:payload.machine_id,title:payload.title,payload,generated:state.result})});const d=await res.json();if(!res.ok)throw new Error(d.detail||'Ошибка');alert('Проект сохранён: #'+d.id)}catch(e){alert(e.message)}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.id===b.dataset.tab))});
$('closeProjects').onclick=()=>$('projectModal').classList.remove('open');$('loadProjects').onclick=async()=>{const tid=+$('telegramId').value,mid=+$('machineId').value;if(!tid||!mid)return alert('Укажите Telegram ID и ID станка.');$('projectModal').classList.add('open');$('projectList').textContent='Загрузка…';try{const res=await fetch(`/api/v1/users/${tid}/machines/${mid}/client-projects`),items=await res.json();if(!res.ok)throw new Error(items.detail||'Ошибка');$('projectList').innerHTML='';items.forEach(item=>{const el=document.createElement('button');el.style.textAlign='left';el.innerHTML=`<b>#${item.id} — ${item.title}</b><br><span class="muted">${new Date(item.updated_at).toLocaleString()}</span>`;el.onclick=()=>loadProject(item);$('projectList').appendChild(el)});if(!items.length)$('projectList').textContent='Сохранённых проектов нет.'}catch(e){$('projectList').textContent=e.message}};function loadProject(item){const p=item.payload||{};$('title').value=p.title||item.title;$('stockD').value=p.stock?.outer_diameter||100;$('stockId').value=p.stock?.inner_diameter||0;$('stockL').value=p.stock?.length||80;$('controller').value=p.machine?.controller||$('controller').value;$('maxRpm').value=p.machine?.max_rpm||3500;state.operations=p.operations||[];renderOperations();state.pdfImage=null;state.origin=null;state.scalePxMm=null;ensureManualFrame();state.pointsPx=(p.contour?.points||[]).map(machineToPixel).filter(Boolean);state.result=item.generated||null;syncContourText();draw();if(state.result)renderResult();$('projectModal').classList.remove('open')}
const qs=new URLSearchParams(location.search);$('telegramId').value=qs.get('telegram_id')||localStorage.telegramId||'';$('machineId').value=qs.get('machine_id')||'';$('telegramId').onchange=()=>localStorage.telegramId=$('telegramId').value;
addOperation('turn_rough');addOperation('turn_finish');
</script>
</body></html>'''
